export enum CityEnum {
	Cherkasy = 'Cherkasy',
	Chernihiv = 'Chernihiv',
	Chernivtsi = 'Chernivtsi',
	Dnipro = 'Dnipro',
	Donetsk = 'Donetsk',
	Ivano_Frankivsk = 'Ivano_Frankivsk',
	Kharkiv = 'Kharkiv',
	Kherson = 'Kherson',
	Khmelnytskyi = 'Khmelnytskyi',
	Kropyvnytskyi = 'Kropyvnytskyi',
	Krym = 'Krym',
	Kyiv = 'Kyiv',
	Luhansk = 'Luhansk',
	Lutsk = 'Lutsk',
	Lviv = 'Lviv',
	Mykolaiv = 'Mykolaiv',
	Odesa = 'Odesa',
	Poltava = 'Poltava',
	Rivne = 'Rivne',
	Sumy = 'Sumy',
	Ternopil = 'Ternopil',
	Uzhhorod = 'Uzhhorod',
	Vinnytsia = 'Vinnytsia',
	Zaporizhzhia = 'Zaporizhzhia',
	Zhytomyr = 'Zhytomyr'
}
